spring:
  datasource:
    url: ${{ DB_URL}}
    username: ${{ DB_USERNAME }}
    password: ${{ DB_PASSWORD }}
    driver-class-name: ${{ DB_DRIVER_CLASS_NAME }}
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
        use_sql_comments: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: update

jwt:
  secretKey: ${{ secrets.JWT_SECRET_KEY }}