spring:
  datasource:
    url: ${{ secrets.DB_URL}}
    username: ${{ secrets.DB_USERNAME }}
    password: ${{ secrets.DB_PASSWORD }}
    driver-class-name: ${{ secrets.DB_DRIVER_CLASS_NAME }}
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
        use_sql_comments: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: update

jwt:
  secretKey: ${{ secrets.JWT_SECRET_KEY }}