name: Spring-Boot-Manito-Amazon EC2

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

#     - name: Configure AWS credentials
#       uses: aws-actions/configure-aws-credentials@v1
#       with:
#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         aws-region: us-west-2 # Or your preferred region

#     - name: Copy files to the testpro user on EC2
#       uses: appleboy/scp-action@master
#       with:
#         host: ${{ secrets.HOST }}
#         username: ${{ secrets.USERNAME }}
#         key: ${{ secrets.SSH_PRIVATE_KEY }}
#         source: "./build/libs/*"
#         target: "/home/testpro/app"

#     - name: Installing CodeDeploy agent on EC2
#       uses: appleboy/ssh-action@master
#       with:
#         host: ${{ secrets.HOST }}
#         username: ${{ secrets.USERNAME }}
#         key: ${{ secrets.SSH_PRIVATE_KEY }}
#         script: "sudo service codedeploy-agent start"

#     - name: Deploy to AWS CodeDeploy
#       id: deploy
#       uses: webfactory/create-aws-codedeploy-deployment@v1.1
#       with:
#         application-name: CodeDeployApplication # CodeDeploy application name
#         deployment-group: DeploymentGroup # CodeDeploy deployment group name
#         revision-type: S3
#         s3-bucket: BucketName # S3 bucket name where the revision is stored
#         s3-key: latest/my-application.zip # S3 object key
#         ignore-application-stop-failures: true
#         wait-until-deployed: true
#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         aws-region: us-west-2 # Or your preferred region
